"""init

Revision ID: 0e88bae8a098
Revises:
Create Date: 2025-09-22 00:46:42.320647

"""

from typing import Sequence, Union
import tzlocal
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e88bae8a098"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "containers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "check_enabled",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column(
            "update_enabled",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column(
            "update_available",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column(
            "checked_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            server_onupdate=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        op.f("ix_containers_name"),
        "containers",
        ["name"],
        unique=False,
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("value_type", sa.String(), nullable=False),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.execute(
        sa.text(
            f"""
        INSERT INTO settings (key, value, value_type) VALUES
        ('CRONTAB_EXPR', '0 */1 * * *', 'str'),
        ('NOTIFICATION_URL', '', 'str'),
        ('TIMEZONE', '{tzlocal.get_localzone_name()}', 'str')
        """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_index(op.f("ix_containers_name"), table_name="containers")
    op.drop_table("containers")
    # ### end Alembic commands ###
