"""init

Revision ID: 0e88bae8a098
Revises: 
Create Date: 2025-09-22 00:46:42.320647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e88bae8a098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('check_enabled', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('update_enabled', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_containers_name'), 'containers', ['name'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.execute(
        sa.text(
            "INSERT INTO settings (key, value, value_type) VALUES ('CRONTAB_EXPR', '* * * * *', 'str')"
        )
    )
    op.execute(
        sa.text(
            "INSERT INTO settings (key, value, value_type) VALUES ('NOTIFICATION_URL', '', 'str')"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_index(op.f('ix_containers_name'), table_name='containers')
    op.drop_table('containers')
    # ### end Alembic commands ###
