"""add_health_monitor_models

Revision ID: 2dbd8767020b
Revises: 8a1627f7ef0d
Create Date: 2026-09-11 03:34:49.742340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

from backend.const import (
    DEFAULT_HEALTH_MONITOR_CRON_EXPR,
    DEFAULT_HEALTH_MONITOR_HISTORY_DAYS,
    DEFAULT_HEALTH_MONITOR_N_TO_NTFY,
    DEFAULT_HEALTH_MONITOR_N_TO_RESTART,
    DEFAULT_HEALTH_MONITOR_NTFY_BODY_TMPL,
    DEFAULT_HEALTH_MONITOR_RESTART_ATTEMPTS,
)

# revision identifiers, used by Alembic.
revision: str = "2dbd8767020b"
down_revision: str | Sequence[str] | None = "8a1627f7ef0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "container_health_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("restarted", sa.Boolean(), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_id"], ["containers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "container_health_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("container_id", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("restart_attempts", sa.Integer(), nullable=False),
        sa.Column("is_notified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_id"], ["containers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_id"),
    )
    # ### end Alembic commands ###

    settings = table(
        "settings",
        column("key", sa.String),
        column("value", sa.String),
        column("value_type", sa.String),
    )
    op.bulk_insert(
        settings,
        [
            {
                "key": "HEALTH_MONITOR_CRON_EXPR",
                "value": DEFAULT_HEALTH_MONITOR_CRON_EXPR,
                "value_type": "str",
            },
            {
                "key": "HEALTH_MONITOR_NTFY_BODY_TMPL",
                "value": DEFAULT_HEALTH_MONITOR_NTFY_BODY_TMPL,
                "value_type": "str",
            },
            {
                "key": "HEALTH_MONITOR_N_TO_RESTART",
                "value": DEFAULT_HEALTH_MONITOR_N_TO_RESTART,
                "value_type": "int",
            },
            {
                "key": "HEALTH_MONITOR_N_TO_NTFY",
                "value": DEFAULT_HEALTH_MONITOR_N_TO_NTFY,
                "value_type": "int",
            },
            {
                "key": "HEALTH_MONITOR_RESTART_ATTEMPTS",
                "value": DEFAULT_HEALTH_MONITOR_RESTART_ATTEMPTS,
                "value_type": "int",
            },
            {
                "key": "HEALTH_MONITOR_HISTORY_DAYS",
                "value": DEFAULT_HEALTH_MONITOR_HISTORY_DAYS,
                "value_type": "int",
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("container_health_state")
    op.drop_table("container_health_history")
    # ### end Alembic commands ###
    op.execute("DELETE FROM settings WHERE key LIKE 'HEALTH_MONITOR_%'")
