"""image digest metadata

Revision ID: 554ba6b3dc03
Revises: d4329b5eca36
Create Date: 2026-10-01 18:23:35.309939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "554ba6b3dc03"
down_revision: str | Sequence[str] | None = "d4329b5eca36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_digests",
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("digest"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image_digests")
    # ### end Alembic commands ###
