"""add_swarm_services_support

Revision ID: d4329b5eca36
Revises: 2dbd8767020b
Create Date: 2026-09-25 02:57:55.207359

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4329b5eca36"
down_revision: str | Sequence[str] | None = "2dbd8767020b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "swarm_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("image_id", sa.String(), nullable=True),
        sa.Column(
            "check_enabled",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column(
            "update_enabled",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column(
            "update_available",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
        ),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("local_digests", sa.JSON(), nullable=True),
        sa.Column("remote_digests", sa.JSON(), nullable=True),
        sa.Column("notified_available_digests", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("swarm_services", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_swarm_services_host_id"), ["host_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swarm_services_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_swarm_services_service_id"), ["service_id"], unique=False
        )

    with op.batch_alter_table("hosts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_swarm",
                sa.Boolean(),
                server_default=sa.text("(FALSE)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("swarm_cluster_id", sa.String(), nullable=True))

    from backend.const import DEFAULT_NOTIFICATION_TEMPLATE
    from backend.modules.settings.settings_enum import ESettingKey

    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE settings SET value = :val WHERE key = :key"),
        {
            "key": ESettingKey.NOTIFICATION_BODY_TEMPLATE.value,
            "val": DEFAULT_NOTIFICATION_TEMPLATE,
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hosts", schema=None) as batch_op:
        batch_op.drop_column("swarm_cluster_id")
        batch_op.drop_column("is_swarm")

    with op.batch_alter_table("swarm_services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_swarm_services_service_id"))
        batch_op.drop_index(batch_op.f("ix_swarm_services_name"))
        batch_op.drop_index(batch_op.f("ix_swarm_services_host_id"))

    op.drop_table("swarm_services")
    # ### end Alembic commands ###
